services:
  app:
    build: .
    container_name: competent_brattain
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - 3000:3000

    command: [ "gunicorn", "--bind", "0.0.0.0:3000", "wsgi" ]
 
        



