version: "3.8"
services:
  app:
    build: .
    command: python3 main.py runserver 0.0.0.0:3000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
        - "3000:3000"
        - "3001:3000"  # Maps port 3001 on the host to port 3000 in the container

        
    






