# Default values for the Helm Chart
---

# Number of replicas required
replicaCount: 2

# Application image and tag
image: samaenany/todolist-depi-project:latest

# Port exposed by application container
containerPort: 3000

# Port to expose by the created service
servicePort: 80

# Resource requests and limits for deployment
cpuRequest: 10m
cpuLimit: 5000m
memoryRequest: 128Mi
memoryLimit: 1Gi

# DB config: this is just to test k8s secret injection into pods. 
# No databases are being deployed by this chart.
db:
  # Set base64-encoded credentials (should be overwritten by chart users)
  username: SKY123AM
  password: SKY123AM

  # Or refer to an existing secret that has keys `username` and `password` 
  existingSecretName: ~

# Configurations for stateful apps
stateful:
  # When enabled, a StatefulSet will be applied instead of a Deployment.
  enabled: false

  # Storage requested by the PVC
  storageRequest: 1Gi